### CREATE PRODUCT
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId": 101,
    "productName": "Mobile",
    "brand": "Samsung",
    "price": 20000
}

###


### GET ALL PRODUCTS
GET http://localhost:3000/product-api/products

###


### GET PRODUCT BY ID
GET http://localhost:3000/product-api/products/101

###


### UPDATE PRODUCT
PUT http://localhost:3000/product-api/products/101
Content-Type: application/json

{
    "productName": "Watch",
    "brand": "Samsung",
    "price": 15000
}

###


### DELETE PRODUCT
DELETE http://localhost:3000/product-api/products/101